language: node_js
node_js:
  - "9"
before_install:
  - "npm config set spin false"
install:
  - npm install

after_success:
  - bash <(curl -s https://scripts.scantist.com/staging/ci-travis-jar.sh)

cache:
  directories:
    - node_modules
